import { Metadata } from 'next';
import Link from 'next/link';
import styles from './layout.module.css';
import { Open_Sans } from 'next/font/google';
import { Nanum_Gothic } from 'next/font/google';

export const metadata: Metadata = {
  title: '제품 사이트 | 전체 제품 확인',
  description: 'Generated by create next app',
};

type props = {
  children: React.ReactNode;
  params: any;
};

export default function Layout({ children, params }: props) {
  return (
    <div>
      <nav className={styles.nav}>
        <Link href='/products/woman'>여성옷</Link>
        <Link href='/products/man'>남성옷</Link>
      </nav>

      {children}
    </div>
  );
}
