import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header>
          <h1>Demo Note App</h1>
          <nav>
            <a href=''>Content</a>
            <a href=''>nav</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
